hospitals/config/routes.rb
Rails.application.routes.draw do
  #general
  get "/" => 'user#entry'

  #USER--------
  get 'user/entry' => 'user#entry'
  post 'user/magia' => 'user#magia'
  get 'user/appmagic' => 'user#appmagic'
  get 'user/mapa' => 'user#mapa'

  #HOSPITAL---------
  get 'hospital/index' => 'hospital#index'
  post 'hospital/procesar' => 'hospital#procesar'

end

hospitals/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hospitals/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

hospitals/app/controllers/hospital_controller.rb
#require 'HTTPClient'
require 'httpclient'
require 'rest-client'

class HospitalController < ApplicationController
  def index
  end

  def procesar
    id = params[:consulta][:id]

    client = HTTPClient.new
    cap = client.get_content('http://130.206.112.201:1026/v2/entities/' + id + '/attrs/capacidad/value')
    camas = client.get_content('http://130.206.112.201:1026/v2/entities/' + id + '/attrs/camas/value')
    @nombre = client.get_content('http://130.206.112.201:1026/v2/entities/' + id + '/attrs/nombre/value')
    @coords = client.get_content('http://130.206.112.201:1026/v2/entities/' + id + '/attrs/coordenadas/value')


    if params[:consulta][:accion] == "1"
      res = cap.to_f + (100.0/camas.to_i)
    else
      res = cap.to_f - (100.0/camas.to_i)
    end


    if res < 0
      res = 0
    end

    @newCap = res

    r = RestClient.put('http://130.206.112.201:1026/v2/entities/' + id + '/attrs/capacidad/value/', res.to_s, content_type: 'text/plain')
  end

end

hospitals/app/controllers/user_controller.rb
#require 'HTTPClient'
require 'httpclient'
require 'rest-client'


class UserController < ApplicationController
  def entry
  end

  def magia
    @coords = params[:uploadLocation][:coordinates]

    pruebaParams = params
    puts pruebaParams


    puts "ahi van las coordenadas"
    puts @coords

    arrCoords = @coords.split(',')
    lat = arrCoords[0]
    long = arrCoords[1]

    compound = lat + ',' + long

    #query = 'http://130.206.112.201:1026/v2/entities?idPattern=.*&type=hospital&georel=near%3BmaxDistance%3A100000&coords=' + compound + '&geometry=point&attrs=capacidad,coordenadas&orderBy=geo%3Adistance&limit=4'
    query = 'http://130.206.112.201:1026/v2/entities?idPattern=.*&type=hospital&georel=near%3BmaxDistance%3A100000&coords=' + compound + '&geometry=point&attrs=capacidad,coordenadas,nombre&orderBy=geo%3Adistance&limit=4'

    queryAmazon = 'http://ataraxia.hopto.org:1026/v2/entities?idPattern=.*&type=hospital&georel=near%3BmaxDistance%3A100000&coords=' + compound + '&geometry=point&attrs=capacidad,coordenadas&orderBy=geo%3Adistance&limit=4'

    client = HTTPClient.new
    response = client.get_content(query)

    puts response

    jasons = JSON.parse response

    lista = Array.new

    #htimes = Hash.new

    for i in 0..3 do
      puts jasons[i]["coordenadas"]["value"]
      lista << jasons[i]["id"]
      puts lista[i]
    end


    #19.435205,-99.1433887

    #Armar las queries
    queries = Array.new
    for i in 0..3 do
      queries << 'https://maps.googleapis.com/maps/api/directions/json?origin=' + compound + '&destination=' + jasons[i]["coordenadas"]["value"] + '&key=AIzaSyCLrYOeMIb8jNP-stoWcN-wrWed7PgDj5k&departure_time=now'
    end

    #ejecutar las queries
    qresults = Array.new
    for i in 0..3 do
      qresults << client.get_content(queries[i])
    end

    #parsear jsons
    rutasData = Array.new
    for i in 0..3 do
      d = JSON.parse qresults[i]
      rutasData << d
    end

    #obtener los tiempos
    tiempos = Array.new
    for i in 0..3 do
      tiempos << rutasData[i]["routes"][0]["legs"][0]["duration_in_traffic"]["value"]
    end

    capacidades = Array.new
    for i in 0..3
      capacidades << jasons[i]["capacidad"]["value"]
    end

    #(100-capacidad)*tiempoAtencion+tiempotraslado
    #tiempoAtencion 25.4 minutos

    puts "CALCULO FUNCION"

    ponderaciones = Array.new
    for i in 0..3
      #p = (100-capacidades[i])*25.4+(tiempos[i]/60)
      p = (capacidades[i] * 0.1) + (tiempos[i]/60)
      ponderaciones << p
    end

    puts ponderaciones

    idMejorHospital = 0
    minActual = 100000
    indice = -1

    for i in 0..3
      if ponderaciones[i] < minActual
        minActual = ponderaciones[i]
        idMejorHospital = jasons[i]["id"]
        indice = i
      end
    end

    puts "Mejor hospital id"
    puts idMejorHospital

    puts "Nombre del mejor hospital"
    puts client.get_content('http://130.206.112.201:1026/v2/entities/' + idMejorHospital + '/attrs/nombre/value')

    #Redirigir al url con las coordenadas del mejor hospital

    coordenadasMejorHospital = client.get_content('http://130.206.112.201:1026/v2/entities/' + idMejorHospital + '/attrs/coordenadas/value')
    coordenadasMejorHospital = coordenadasMejorHospital[1,coordenadasMejorHospital.length].chomp('"')


    mapsURL = 'https://www.google.com/maps/dir/?api=1&origin=' + compound + '&destination=' +coordenadasMejorHospital
    reset_session
    redirect_to(mapsURL)




=begin
https://maps.googleapis.com/maps/api/directions/json?origin=19.344935,-99.199929&destination=19.358603,-99.155045&key=AIzaSyCLrYOeMIb8jNP-stoWcN-wrWed7PgDj5k&departure_time=now

=end



  end

  def appmagic

    latitud = params[:lat]
    longitud = params[:long]



    puts "ahi va latlong"
    puts latitud
    puts longitud

    compound = latitud + ',' + longitud

    query = 'http://130.206.112.201:1026/v2/entities?idPattern=.*&type=hospital&georel=near%3BmaxDistance%3A100000&coords=' + compound + '&geometry=point&attrs=capacidad,coordenadas,nombre&orderBy=geo%3Adistance&limit=4'



    client = HTTPClient.new
    response = client.get_content(query)

    puts response

    jasons = JSON.parse response

    lista = Array.new

    for i in 0..3 do
      puts jasons[i]["coordenadas"]["value"]
      lista << jasons[i]["id"]
      puts lista[i]
    end


    #19.435205,-99.1433887

    #Armar las queries
    queries = Array.new
    for i in 0..3 do
      queries << 'https://maps.googleapis.com/maps/api/directions/json?origin=' + compound + '&destination=' + jasons[i]["coordenadas"]["value"] + '&key=AIzaSyCLrYOeMIb8jNP-stoWcN-wrWed7PgDj5k&departure_time=now'
    end

    #ejecutar las queries
    qresults = Array.new
    for i in 0..3 do
      qresults << client.get_content(queries[i])
    end

    #parsear jsons
    rutasData = Array.new
    for i in 0..3 do
      d = JSON.parse qresults[i]
      rutasData << d
    end

    #obtener los tiempos
    tiempos = Array.new
    for i in 0..3 do
      tiempos << rutasData[i]["routes"][0]["legs"][0]["duration_in_traffic"]["value"]
    end

    capacidades = Array.new
    for i in 0..3
      capacidades << jasons[i]["capacidad"]["value"]
    end

    #(100-capacidad)*tiempoAtencion+tiempotraslado
    #tiempoAtencion 25.4 minutos

    puts "CALCULO FUNCION!!!!"

    ponderaciones = Array.new
    for i in 0..3
      #p = (100-capacidades[i])*25.4+(tiempos[i]/60)
      p = (capacidades[i] * 0.1) + (tiempos[i]/60)
      ponderaciones << p
    end

    puts ponderaciones

    idMejorHospital = 0
    minActual = 100000
    indice = -1

    for i in 0..3
      if ponderaciones[i] < minActual
        minActual = ponderaciones[i]
        idMejorHospital = jasons[i]["id"]
        indice = i
      end
    end

    puts "Mejor hospital id"
    puts idMejorHospital

    puts "Nombre del mejor hospital"
    puts client.get_content('http://130.206.112.201:1026/v2/entities/' + idMejorHospital + '/attrs/nombre/value')

    #Redirigir al url con las coordenadas del mejor hospital

    coordenadasMejorHospital = client.get_content('http://130.206.112.201:1026/v2/entities/' + idMejorHospital + '/attrs/coordenadas/value')
    coordenadasMejorHospital = coordenadasMejorHospital[1,coordenadasMejorHospital.length].chomp('"')

    @coordResults = coordenadasMejorHospital

    #19.435205,-99.1433887
    #?lat=19.435205&long=-99.1433887





  end

  def mapa
  end

end

hospitals/app/helpers/application_helper.rb
module ApplicationHelper
end

hospitals/app/helpers/hospital_helper.rb
module HospitalHelper
end

hospitals/app/helpers/user_helper.rb
module UserHelper
end

hospitals/app/views/hospital/index.html.erb
<head>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<h1>Panel Hospital</h1>

<%= form_for :consulta, url: hospital_procesar_path do |f|%>
  <div class="form-group jumbotron container">
      <h3 id="h1T">Hola, introduce el hospital y la accion que deseas realizar</h3>
   <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <div class="row">

        <div class="col-lg-6">
          <p>
           <%= f.label :id %><br>
           <%= f.text_field :id, required: true %>
           </p>
           <p>
             <%= f.radio_button :accion, '0', required: true%>
             <%= label_tag(:accion_decrementa, "Salida de paciente")%> <br>
               <%= f.radio_button :accion, '1', required: true%>
               <%= label_tag(:accion_incrementa, "Entrada de paciente")%>
           </p>
        </div>

      </div>

      <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">

          <p>
          <%= f.submit("Actualizar") %>
          </p>
          <% end %>

hospitals/app/views/hospital/procesar.html.erb
<h1><%="Hospital " + @nombre %></h1>

<iframe width="300" height="300" frameborder="0" style="border:0"
 src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCOsmp8KepU28OraNWZUGPw5SlCuhJJPGk&q=<%=@coords%>"
 allowfullscreen>
</iframe>

<p>La capacidad actualizada es de <b><%=@newCap.round(2)%></b>%</p>

hospitals/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospitals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hospitals/app/views/user/appmagic.html.erb
<%=@coordResults%>

hospitals/app/views/user/entry.html.erb
<!DOCTYPE html>
<html>
<body onload="getLocation();">

<%= form_for :uploadLocation, url: user_magia_path do |f|%>

  <p>
  <%= f.label :coordinates %>
  <%= f.text_field :coordinates, required: true, id: "coordinates"%>
  </p>
  <%= f.submit("Mandar ubicacion") %>

<% end %>

<script>
var x = document.getElementById("coordinates");

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.watchPosition(showPosition);
    } else {
        x.value = "Geolocation is not supported by this browser.";}
    }

function showPosition(position) {
    x.value = position.coords.latitude + "," + position.coords.longitude;
}
</script>

</body>
</html>

hospitals/app/views/user/mapa.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Hospitales</title>
    <link rel="stylesheet" href="dist/css/bootstrap.min.css">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">



    </script>


      <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 95%;
        margin: 0;
        padding: 0;
      }
    </style>

 </head>

 <body style="margin-left:100px;margin-left:auto;margin-right:auto;">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Hospital</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <!--<li><a onclick="abrir()"  href="#">JSON</a></li>
-->
  </ul>

  <ul class="nav navbar-nav navbar-right">
      <li><a href="#" onclick="salir()">Salir</a></li>

  </ul>
</div><!-- /.navbar-collapse -->
</nav>
    <div id="map"></div>
<script type="text/javascript">
   //document.open('index.html','nueva','width=300,height=400');
    //RegresaRonda();
//    recibeInfo();
//    var contador=0;
//    var intervaloR;
    </script>

    <script>
      // Note: This example requires that you consent to location sharing when
      // prompted by your browser. If you see the error "The Geolocation service
      // failed.", it means you probably did not give permission for the browser to
      // locate you.
      var map, infoWindow;
      function initMap() {
          var directionsDisplay = new google.maps.DirectionsRenderer;
        var directionsService = new google.maps.DirectionsService;

        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 20.6264252, lng: -105.2314634},
          zoom: 14
        });
              directionsDisplay.setMap(map);

        infoWindow = new google.maps.InfoWindow;

        // Try HTML5 geolocation.
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            fnWeb(pos,map,directionsService, directionsDisplay)
            infoWindow.setPosition(pos);
            infoWindow.setContent('Mi ubicación');
            infoWindow.open(map);
            map.setCenter(pos);
          }, function() {
            handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          handleLocationError(false, infoWindow, map.getCenter());
        }
 directionsDisplay.setMap(map);



      }



      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
      }


    function calculateAndDisplayRoute(directionsService,directionsDisplay,coordOrigin, coordDestino) {
        var selectedMode = 'DRIVING';
        directionsService.route({
          origin: coordOrigin,
          destination: coordDestino,  // Haight.  // Ocean Beach.
          // Note that Javascript allows us to access the constant
          // using square brackets and a string value as its
          // "property."
          travelMode: google.maps.TravelMode[selectedMode]
        }, function(response, status) {
          if (status == 'OK') {
            directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      }

var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
var icons = {
  parking: {
    icon: iconBase + 'parking_lot_maps.png'
  },
  library: {
    icon: iconBase + 'library_maps.png'
  },
  info: {
    icon: iconBase + 'info-i_maps.png'
  },
  hospital: {
    icon: iconBase + 'Hospitales.png'
  }
};


      function fnWeb(pos,map,directionsService, directionsDisplay){
        console.log(pos)

          $.ajax({
                url: 'http://0.0.0.0:3000/user/appmagic?lat='+pos.lat+'&long='+pos.lng,//20?usr='+usr+'&psw='+psw,
                dataType: "json",
                success: function (data) {
                    //valido la respuesta del json para enviar una notificacion al empleado, si es 0 quiere decir que los datos introducidos son incorrectos si es uno se ejecuto correctamente
                    //se tiene que cambair solo la dispensa
                   alert("a huevo")
                },
                error: function (result) {
                    alert("ya mame");
                }
            });


         var coordOrigin = {lat:  pos.lat, lng: pos.lng };
         var coordDestino = {lat:  20.6372734, lng: -105.203252};  // Haight.  // Ocean Beach.


    var infowindow = new google.maps.InfoWindow();
    var marker, i;
    var markers = new Array();
    for (i = 0; i < locations.length; i++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        icon : 'https://maps.google.com/mapfiles/kml/shapes/hospitals.png',
        map: map
      });

      markers.push(marker);
      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));


        calculateAndDisplayRoute(directionsService, directionsDisplay,coordOrigin, coordDestino);
  }

/*
       var contentString = '<div id="content">'+
            '<div id="siteNotice">'+
            '</div>'+
            '<h1 id="firstHeading" class="firstHeading">Uluru</h1>'+
            '<div id="bodyContent">'+
            '<p><b>Uluru</b>, also referred to as <b>Ayers Rock</b>, is a large ' +
            'sandstone rock formation in the southern part of the '+
            'Northern Territory, central Australia. It lies 335&#160;km (208&#160;mi) '+
            'south west of the nearest large town, Alice Springs; 450&#160;km '+
            '(280&#160;mi) by road. Kata Tjuta and Uluru are the two major '+
            'features of the Uluru - Kata Tjuta National Park. Uluru is '+
            'sacred to the Pitjantjatjara and Yankunytjatjara, the '+
            'Aboriginal people of the area. It has many springs, waterholes, '+
            'rock caves and ancient paintings. Uluru is listed as a World '+
            'Heritage Site.</p>'+
            '<p>Attribution: Uluru, <a href="https://en.wikipedia.org/w/index.php?title=Uluru&oldid=297882194">'+
            'https://en.wikipedia.org/w/index.php?title=Uluru</a> '+
            '(last visited June 22, 2009).</p>'+
            '</div>'+
            '</div>';

        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map,
          title: 'Uluru (Ayers Rock)'
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });*/
      }
/*
      $.ajax({
            url: 'http://ataraxia.hopto.org:3000/users/appmagic?lat=19&lon=20',
            data: {
                q: "select * from json where url ='http://valet.itam.mx/MVC/Reporte/getSolicitud?cu="+ cu + "&lugar=" + lugar + "&tipo=" + tipo + "&comentario=" + comentario +"&urgente="+ urgente.checked + "&detallelugar=" + detalle + "&correo="+ correo +"'" ,
                format: "json"
            },
            dataType: "jsonp",
            success: function (data) {
                //obtenemos el resultado del json
                res = data.query.results.Respuesta.toString();

                //Si la solicitud fue enviada correctamente regresa algo distinto de 0
                if(res != "0"){
                    //el json se recibio correctamente y se redireccionara a uan ventana dando un texto de agradecimiento
                    window.location="recomendacion.html"
                }else{
                    //el json nos e pudo recibir , direccionamos a otra página donde mostrara un anucio de error
                    window.location="error.html"
                }

            },
            error: function (result) {
                alert("Error de conección");
            }
        });
* /

    function conectaserver(lat,long){

        $.ajax({
                url: 'http://ataraxia.hopto.org:3000/users/appmagic?lat='+lat+'&long='long,//20?usr='+usr+'&psw='+psw,
                dataType: "json",
                success: function (data) {
                    //valido la respuesta del json para enviar una notificacion al empleado, si es 0 quiere decir que los datos introducidos son incorrectos si es uno se ejecuto correctamente
                    //se tiene que cambair solo la dispensa
                    document.getElementById("alerta").innerHTML="Se uso una dispensa";
                    recibeInfo();

                },
                error: function (result) {
                    document.getElementById("alerta").innerHTML="Error al usar una dispensa";
                }
            });
    }*/

    var locations = [
      ['Regional de Vallarta', 20.6372734, -105.203252, 4],
      ['San Javier Marina', 20.6436105, -105.2183796, 5],
      ['Hospital ISSTE', 20.6455402, -105.2421891, 3],
      ['Hospital Versalles', 20.6671352, -105.2081502, 2]
    ];
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDsVevAurzrOWW05ncK40KhSXjOPRq134c&callback=initMap">
    </script>
  </body>
</html>